[package]
name = "rusty-8"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
codegen-units = 1

[dependencies]
nanorand = "0.6.1"
mini_gl_fb = "0.9.0"
rodio = "0.14.0"